export * from "./About/About"
export * from "./Education/Education"
export * from "./Experience/Experience"
export * from "./Mario/Mario"
export * from "./More/More"
export * from "./Separador/Separador"